# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: mkdir
      run: mkdir ${HOME}/.m2/ -p
    - name: checkout
      run: wget https://github.com/pentaho/pentaho-kettle/archive/refs/tags/10.3.0.0-25.zip -O pentaho-kettle-10.3.0.0-25.zip
    - name: unzip
      run: unzip pentaho-kettle-10.3.0.0-25.zip
    - name: download settings
      run: wget https://raw.githubusercontent.com/pentaho/maven-parent-poms/master/maven-support-files/settings.xml -O ${HOME}/.m2/settings.xml
    - name: move
      run: pentaho-kettle-10.3.0.0-25 /home/runner/work/pentaho-kettle/pentaho-kettle
    - name: cd
      run: cd /home/runner/work/pentaho-kettle/pentaho-kettle
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: tree
      run: tree assemblies/client/target/
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: assemblies/client/target/pdi-ce-*-SNAPSHOT.zip
        retention-days: 5
